### ISSUE TITLE
neo4j on OpenShift

### ISSUE THREAD

**Issue by mkm29** [bitnami/bitnami-docker-neo4j#5]
Hi, I am trying to get the Bitnami Neo4j image running on OpenShift (testing on my local Minishift), but I am unable to connect. I am following the steps outlined in this [issue](https://github.com/bitnami/bitnami-docker-neo4j/issues/3) (now closed), however, now I cannot access the external IP for the load balancer. 

Here are the steps I have taken:

1.  Deploy Image (bitnami/neo4j)
2. Create service for the load balancer, using the YAML supplied in the issue mentioned
3. Get the external IP address for the LB (oc get services)

The command in step 3 lists 2 of the same IP addresses, and when I attempt to go to this IP in my browser it times out.

**Comment by andresbono** [comment]
Hi @mkm29, did you try to do`kubectl port-forward ...` over the pod to debug the issue? That command can be useful for you in order to find the issue. Let us know what is the result you get from it if you need further help.

**Comment by mkm29** [comment]
Hi @andresbono thanks for the response! Port 31221 on the LB is forwarded to port 7474 of the neo4j pod, so I am trying to run `sudo kubectl port-forward neo4j-1-2qnnd 80:31221` however, the command just hangs at `Forwarding from [::1]:80 -> 31221`

Also, I am on a Mac (10.15.2)

**Comment by javsalgar** [comment]
Hi,

If you are executing port-forward over the pod, would need to set 8080:7474 instead. Could you try that? The command does not "hang" but instead does the port forwarding (so you can access the port in another terminal or using your browser) until you execute CTRL-C

**Comment by mkm29** [comment]
Thanks, @javsalgar, unfortunately, that did not work, I am attempting to go to the external IP of the LB at port 8080 but same result :(

**Comment by javsalgar** [comment]
Hi,

If you execute port-forward then you should access 127.0.0.1:8080. Could you try that?

**Comment by mkm29** [comment]
Thanks! Using that I was able to connect to the browser/GUI, but when trying to connect with username neo4j and password bitnami I am still getting the error: "ServiceUnavailable: WebSocket connection failure. Due to security constraints in your web browser, the reason for the failure is not available to this Neo4j Driver. Please use your browsers development "

**Comment by javsalgar** [comment]
Hi,

Could you see in the browser web inspector which address it is triying to access? Maybe you need to port-forward 7474 to 7474

**Comment by mkm29** [comment]
Hi, how do I determine which address it is trying to access? When I run `oc port-forward neo4j-1-2qnnd 7474:7474` I get the same error when logging in at 127.0.0.1:7474

**Comment by javsalgar** [comment]
I would check the chrome inspector console to see if there are any error messages

![image](https://user-images.githubusercontent.com/1133777/71509948-6d736400-288d-11ea-9fbe-fb3c0b1391cc.png)

**Comment by mkm29** [comment]
I get this error: `neo4j-driver.chunkhash.bundle.js:1 WebSocket connection to 'ws://127.0.0.1:7687/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED`

Do I need to uncomment out this config line?

https://neo4j.com/developer/kb/explanation-of-error-websocket-connection-failure/

**Comment by mkm29** [comment]
I finally got it resolved. If you uncomment that line (actually does not appear to even be contained in the conf file) by setting an environment variable NEO4J_dbms_connector_bolt_address=0.0.0.0:7687 AND forward port 7474 it works without the need of a load balancer

**Comment by mkm29** [comment]
I take that back; that fixed it and I was able to log in two or three times, but now I am getting the same error. Strange. I have tried a lot of things including creating a load balancer and setting some environment variables but no success...

**Comment by javsalgar** [comment]
Do you know if the container got restarted? Do you see the environment variable set if you enter the container with kubectl exec? Could it be an issue with the persistence?

**Comment by mkm29** [comment]
I am not sure if the container got restarted, but I do see the environment variable in the pod, here is full print out of the env vars:

`KUBERNETES_SERVICE_PORT=443
KUBERNETES_PORT=tcp://172.30.0.1:443
NEO4J_SERVICE_PORT_7473_TCP=7473
NEO4J_PORT_7473_TCP=tcp://172.30.47.66:7473
NAMI_VERSION=1.0.0-1
NEO4J_SERVICE_PORT_7474_TCP=7474
NEO4J_PORT_7474_TCP=tcp://172.30.47.66:7474
HOSTNAME=neo4j-1-82sfc
HOME=/
NEO4J_PORT_8756_TCP=tcp://172.30.47.66:8756
NEO4J_SERVICE_PORT_8756_TCP=8756
NEO4J_BOLT_PORT_NUMBER=7687
BITNAMI_PKG_CHMOD=-R g+rwX
BITNAMI_APP_NAME=neo4j
BITNAMI_IMAGE_VERSION=3.5.14-debian-9-r9
GPG_KEY_SERVERS_LIST=ha.pool.sks-keyservers.net                          hkp://p80.pool.sks-keyservers.net:80                          keyserver.ubuntu.com                          hkp://keyserver.ubuntu.com:80                          pgp.mit.edu
TERM=xterm
KUBERNETES_PORT_443_TCP_ADDR=172.30.0.1
PATH=/opt/bitnami/java/bin:/opt/bitnami/neo4j/bin:/opt/bitnami/nami/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
NEO4J_PASSWORD=bitnami
KUBERNETES_PORT_443_TCP_PORT=443
KUBERNETES_PORT_443_TCP_PROTO=tcp
NEO4J_HTTP_PORT_NUMBER=7474
NEO4J_dbms_connector_bolt_address=0.0.0.0:7687
NEO4J_SERVICE_HOST=172.30.47.66
NEO4J_HOST=
IMAGE_OS=debian-9
NEO4J_HTTPS_PORT_NUMBER=7473
NEO4J_PORT_7473_TCP_ADDR=172.30.47.66
NEO4J_PORT_7474_TCP_ADDR=172.30.47.66
KUBERNETES_SERVICE_PORT_HTTPS=443
NEO4J_PORT=tcp://172.30.47.66:7473
KUBERNETES_PORT_443_TCP=tcp://172.30.0.1:443
NEO4J_SERVICE_PORT=7473
NAMI_PREFIX=/.nami
NEO4J_PORT_7473_TCP_PORT=7473
GOSU_VERSION=1.10
GOSU_GPG_KEY=B42F6819007F00F88E364FD4036A9C25BF357DD4
NEO4J_PORT_7473_TCP_PROTO=tcp
KUBERNETES_SERVICE_HOST=172.30.0.1
NEO4J_PORT_7474_TCP_PORT=7474
PWD=/
NEO4J_PORT_7474_TCP_PROTO=tcp
NEO4J_PORT_8756_TCP_ADDR=172.30.47.66
TINI_VERSION=v0.13.2
TINI_GPG_KEY=595E85A6B1B4779EA4DAAEC70B588DFF0527A9B7
NEO4J_PORT_8756_TCP_PORT=8756
NEO4J_PORT_8756_TCP_PROTO=tcp`

**Comment by mkm29** [comment]
Did you say you got Neo4j deployed on OpenSift? Which version of Neo and OC?

**Comment by javsalgar** [comment]
Hi,

I was able to make it work by port-forwarding both 7474 and 7687

![image](https://user-images.githubusercontent.com/1133777/71618586-85feb980-2bc0-11ea-9309-8a8af0089d05.png)

**Comment by mkm29** [comment]
You rock! With the LB and those 2 ports forwarded I was able to connect. I am relatively new to Kubernetes/OpenShift, so I was wondering if there is a way to "permanently" forward ports in OpenShift, similarly to running a container in the background/detached mode? Thanks.

**Comment by mkm29** [comment]
Props. I got it deployed on our OpenShift successfully. Thanks again!
