### ISSUE TITLE
latest version of neo4j image is pointing to something else which uses java 8 (new plugins can't be installed)

### ISSUE THREAD

**Issue by fssrepository** [bitnami/bitnami-docker-neo4j#6]
latest version of neo4j image is pointing to something else (not 4.0.4) which uses java 8 (new plugins can't be installed)

**Comment by carrodher** [comment]
Hi, it seems you closed the issue because you found the correct version, just to close the loop, using the latest image:

```console
$ java --version
openjdk 11.0.7 2020-04-14 LTS
OpenJDK Runtime Environment (build 11.0.7+10-LTS)
OpenJDK 64-Bit Server VM (build 11.0.7+10-LTS, mixed mode)

$ neo4j --version
neo4j 4.0.4
```

Thanks for using the Bitnami containers

**Comment by fssrepository** [comment]
I had a prehistoric latest version, which hasn't been upgraded by the
latest it seems. It was 6 month old. Removing it, and put 4.0.4 instead of
latest solved the problem.
